### ISSUE TITLE
Persistent Internet Sharing does not work.

### ISSUE THREAD

**Issue by tasagore** [micahmo/WireGuardServerForWindows#17]
Windows 2012R2 server (primary domain controller), all works fine but click in the "Enable" button for Persistent Internet Sharing does nothing so if the machine reboots Wireguard will not work. No error in event viewer.

I've seen a lot of post with this issue in Windows 10 that suggest change the key HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\SharedAccess but that key doesn't exists in 2012R2, don't know if this app uses that way.

**Comment by micahmo** [comment]
Hi @tasagore,

Persistent Internet Sharing is notoriously buggy on Windows anyway. I suggest you use [this workaround described in the README](https://github.com/micahmo/WireGuardServerForWindows#known-issues). You can create a scheduled task in Windows Task Scheduler that invokes the WS4W CLI on startup. That will disable and re-enable Internet Sharing, essentially ensuring that it survives a restart.

I should probably build the workaround directly into the app eventually... :)

**Comment by 395122662** [comment]
改注册表解决了。https://blog.csdn.net/qq_33423418/article/details/112170736

**Comment by reyaz006** [comment]
For me the Internet sharing block throws a error when pressing the Enable button. Though it paints itself green when I set the sharing option by hand, but the Persistent internet sharing doesn't do anything when I press its Enable button.

**Comment by micahmo** [comment]
Is it by any chance this error described in the README?

https://github.com/micahmo/WgServerforWindows?tab=readme-ov-file#inability-to-enable-internet-sharing

**Comment by reyaz006** [comment]
No, the error is "Specified cast is not valid".

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Specified cast is not valid.
   at NETCONLib.NetSharingManagerClass.get_INetSharingConfigurationForINetConnection(INetConnection pNetConnection)
   at WgServerforWindows.Models.InternetSharingPrerequisite.<>c__DisplayClass5_0.<Resolve>b__1(INetConnection n) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 63
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at WgServerforWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 61
   at WgServerforWindows.Models.InternetSharingPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 52
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.InvalidCastException: Specified cast is not valid.
   at NETCONLib.NetSharingManagerClass.get_INetSharingConfigurationForINetConnection(INetConnection pNetConnection)
   at WgServerforWindows.Models.InternetSharingPrerequisite.<>c__DisplayClass5_0.<Resolve>b__1(INetConnection n) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 63
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at WgServerforWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 61
   at WgServerforWindows.Models.InternetSharingPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\InternetSharingPrerequisite.cs:line 52
```
