### ISSUE TITLE
Internet sharing is not enabled

### ISSUE THREAD

**Issue by shahriar-shojib** [micahmo/WireGuardServerForWindows#19]
Hello, 
I can't enable internet sharing, when I click enable I get the following error:

```c#
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Specified cast is not valid.
   at NETCONLib.NetSharingManagerClass.get_INetSharingConfigurationForINetConnection(INetConnection pNetConnection)
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.<>c__DisplayClass5_0.<Resolve>b__1(INetConnection n) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 62
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 60
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 51
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.InvalidCastException: Specified cast is not valid.
   at NETCONLib.NetSharingManagerClass.get_INetSharingConfigurationForINetConnection(INetConnection pNetConnection)
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.<>c__DisplayClass5_0.<Resolve>b__1(INetConnection n) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 62
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 60
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 51


```

**Comment by shahriar-shojib** [comment]
got it fixed by enabling internet sharing on the interface manually

**Comment by micahmo** [comment]
Hey @shahriar-shojib, good find! Yes, Internet Sharing in Windows is very picky, and sometimes the only way to fix it is by manually editing the interfaces.

BTW, using `New-NetNat` instead of Internet Sharing, as suggested in #18, should hopefully solve a lot of these issues. I hope to add that before too long.
