### ISSUE TITLE
NAT Routing Error

### ISSUE THREAD

**Issue by crack00r** [micahmo/WireGuardServerForWindows#30]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: New-NetNat : Ungltige Klasse 
In Zeile:1 Zeichen:1
+ New-NetNat -Name wg_server_nat -InternalIPInterfaceAddressPrefix 10.2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (MSFT_NetNat:root/StandardCimv2/MSFT_NetNat) [New-NetNat], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,New-NetNat
 

   at WireGuardServerForWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\NewNetNatPrerequisite.cs:line 115
   at WireGuardServerForWindows.Models.NewNetNatPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\NewNetNatPrerequisite.cs:line 68
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.Exception: New-NetNat : Ungltige Klasse 
In Zeile:1 Zeichen:1
+ New-NetNat -Name wg_server_nat -InternalIPInterfaceAddressPrefix 10.2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (MSFT_NetNat:root/StandardCimv2/MSFT_NetNat) [New-NetNat], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,New-NetNat
 

   at WireGuardServerForWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\NewNetNatPrerequisite.cs:line 115
   at WireGuardServerForWindows.Models.NewNetNatPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\NewNetNatPrerequisite.cs:line 68

**Comment by micahmo** [comment]
Hey @crack00r, can you send the exact version of Windows you're running? From the Start menu or Run box, type `winver` and screenshot the window. It should look something like this.

![image](https://user-images.githubusercontent.com/7417301/161405783-4333fb5f-c7f8-4289-bd77-57a3bf0407c5.png)

Thanks!

**Comment by micahmo** [comment]
@crack00r I would still like to hear what version of Windows you're running, but I think I know what's going on here. The NAT routing features requires either...
* Hyper-V to be enabled (which requires Pro)
* Or Windows to be updated to 21H2

Of course Internet Connection Sharing can always be used if NAT cannot.

I've documented this limitation [here](https://github.com/micahmo/WireGuardServerForWindows#inability-to-enable-nat). 

I will keep the issue open to track an enhancement, which should do the following.
* On a Windows installation capable of (but not currently) running Hyper-V, automatically enable it.
* On a Windows installation incapable of running Hyper-V, do not show the NAT option.

**Comment by crack00r** [comment]
sure, here you go

With the Connection Sharing it works perfect!

![image](https://user-images.githubusercontent.com/6163329/161415173-4d4ed415-079e-4fc6-af4c-cd2039867121.png)

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/161415436-f4e08aa3-389f-45bb-a545-e726d76d4e82.png)

**Comment by micahmo** [comment]
Thanks for confirming! This aligns with my guess.
1. You have version 21H1, so the NAT routing feature won't work without Hyper-V
2. And you have Home, which means you can't enable Hyper-V anyway

I'm glad to hear that ICS works. And if you did want to use NAT instead (it has some benefits described in #18), you could update to 21H2.

As mentioned, I will keep this issue open, because the NAT button should not have been available in your scenario.

**Comment by micahmo** [comment]
Upon further investigation (with Windows 10 Pro 21H2), it appears that Hyper-V must be enabled in order to use NAT Routing. @kenvix, you said in #18 that it didn't. Can you explain how you got `New-NetNat` to work without first enabling Hyper-V?

For now, I've updated the documentation to reflect this.
https://github.com/micahmo/WireGuardServerForWindows#inability-to-enable-nat

**Comment by micahmo** [comment]
Hmm, interesting. Now I wonder if my problem could've been related to the fact that I was using VMs to test this without nested virtualization enabled. I will have to do some more investigation.

**Comment by micahmo** [comment]
I'm getting the impression that I won't be able to add a simple version check to gate this feature. 😊

It seems like I will need some sort of graceful handling of this error that does the following...
1. Try to enable NAT Rounting.
2. If it fails, try to enable Hyper-V.
3. If that fails, direct users to Internet Connection Sharing instead.

**Comment by micahmo** [comment]
Hey all, I just pushed [v1.7.2](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.2) which should help to address this issue. As we collectively discovered, there's not a great way to know upfront whether NAT Routing will work or not, so the application just tries to enable it (with the option to try to enable Hyper-V as well); otherwise, it directs you to use ICS.
